version: "3.8"

services:
  clickhouse:
    image: docker.io/bitnami/clickhouse:24.12.1
    environment:
      - CLICKHOUSE_ADMIN_USER=clickhouse
      - CLICKHOUSE_ADMIN_PASSWORD=secret
    ports:
      - "9000:9000"
      - "8123:8123"
